export const usersData = [
  {
    id: 1,
    name: 'Kasia',
    login: 'kasia',
    email: 'kasia1@gmail.com',
    password: 'kasia',
    twoStepLogin: true,
    profilePhoto: '../../../assets/images/profile-1.jpg',
  },
  {
    id: 2,
    name: 'Janek Kowalski',
    login: 'jkowalski',
    email: 'j@kowalski.pl',
    password: 'fajnehasło123',
    twoStepLogin: true,
    profilePhoto: '../../../assets/images/profile-2.jpg',
  },
  {
    id: 3,
    name: 'Piotr Nowak',
    login: 'piotreczek',
    email: 'piotrnow@gmail.com',
    password: 'hasłomasło',
    twoStepLogin: true,
    profilePhoto: '../../../assets/images/profile-3.jpg',
  },
  {
    id: 4,
    name: 'Krzysiek',
    login: 'krzysiek',
    email: 'cris@poczta.pl',
    password: 'vk18%U^',
    twoStepLogin: true,
    profilePhoto: '../../../assets/images/profile-4.jpg',
  },
  {
    id: 5,
    name: 'Karol Test',
    login: 'testuje',
    email: 'karoltest@gmail.com',
    password: 'qwerty1234',
    twoStepLogin: true,
    profilePhoto: '../../../assets/images/profile-photo.jpg',
  },
];
